### PR TITLE
Add Messenger section and remove OTR

### PR DESCRIPTION
**Pull request by kimg45**
- replace OTR recommendation with superior OMEMO signal protocol-based double-ratchet encryption for XMPP
- remove chat clients which all haven't been updated in years and replace with official [XMPP recommendations](https://xmpp.org/getting-started/)
- add instructions on the most secure way to use iMessage

### CODE REVIEW

**Comment by drduh** [comment]
Does it need to be updated? Are there any known vulnerabilities or other problems with the spec, or applications used? I'd like to hear some stronger arguments against OTR first, other than its age or lack of popularity. It is also a shame to throw out XMPP with it. We should at least replace it with a stronger modern recommendation, if warranted.

**Comment by kimg45** [comment]
Cryptography and messengers move fast, you can't afford to be relying on a protocol that hasn't been updated in 8 years seemingly. There are many better options that I think we should recommend.

XMPP is still good, we can add that if you want. I don't use it so I don't know any clients to recommend, but [XMPP](https://xmpp.org/getting-started/) themselves seem to have a curated list of clients.

**Comment by beerisgood** [comment]
I would replace the whole OTR section with a Messenger section.

For chatting with other Apple devices iMessage with new [PQ3 ](https://security.apple.com/blog/imessage-pq3/) is the most secure. For chatting with non-Apple devices is Signal, but Signal sadly [use](https://www.electronjs.org/apps) Electron on macOS which itself isn't secure [1].

[1]
https://wojciechregula.blog/post/abusing-electron-apps-to-bypass-macos-security-controls/
https://medium.com/@metnew/why-electron-apps-cant-store-your-secrets-confidentially-inspect-option-a49950d6d51f
https://blog.xpnsec.com/macos-injection-via-third-party-frameworks/
https://wojciechregula.blog/post/electroniz3r/

**Comment by kimg45** [comment]
I understand your reservations, however iMessage is part of the system and people are going to use it anyway, so I think this guide should at least cover the most secure way to use it. Doesn't have to necessarily be a recommendation, just let people know that if they choose to use it, here's how they should configure it.

Signal is an excellent messenger, but the desktop client isn't a standalone thing and it requires you to sign up with the phone app first and basically sync your messages to the desktop. It's sort of just a box-ticking exercise so they can say they have a desktop client but you're better off just using it on your phone by itself.

**Comment by jvoisin** [comment]
I would recommend OMEO for XMPP users, and Signal otherwise. Of course, it depends on your threat model. If you don't want the NSA to read your chats, I wouldn't bet on OTR. If you're trying to ensure the person running your XMPP server doesn't have access, OTR is enough.

I don't know anything about the Apple ecosystem, so no clue about iMessage.

**Comment by beerisgood** [comment]
@drduh The number of CVEs has nothing to do with security in first place.
But anyway the more the code is (regularly) checked, the higher the security against unknown gaps.

Also remember that using/ installing non internal programs increase the attack surface so for macOS the best messenger in terms of security is iMessage. Also it's the same for privacy as it's not needed to trust another party.

**Comment by kimg45** [comment]
So yeah no reason to recommend an inferior encryption protocol when a better one exists.

**Comment by drduh** [comment]
> @drduh The number of CVEs has nothing to do with security in first place. But anyway the more the code is (regularly) checked, the higher the security against unknown gaps.

Disagree, especially because the CVEs are being discovered by outside researchers - even without access to source code. As far as I know, the code has never been audited independently, it's closed and proprietary. Are there any third party sources to cite in favor of iMessage security?

> Also remember that using/ installing non internal programs increase the attack surface so for macOS the best messenger in terms of security is iMessage. Also it's the same for privacy as it's not needed to trust another party.

Perhaps, but the CVEs listed also demonstrate risks from using iMessage without Lockdown mode, and very severe ones. I don't understand the privacy argument. To me, it makes more sense for the software which handles cryptography to be different from the one doing the storage and delivery.

The security and privacy trade-offs with trusting Apple software ought to be better explained before the recommendation is made.

**Comment by beerisgood** [comment]
> Disagree, especially because the CVEs are being discovered by outside researchers - even without access to source code. As far as I know, the code has never been audited independently, it's closed and proprietary.
> 
This isn’t a problem. Mostly „outside“ researchers are the ones who find CVEs in closed sources and sometimes even Reverse Engineering the Code so I can’t understand what you’re trying to argument here. 

> Perhaps, but the CVEs listed also demonstrate risks from using iMessage without Lockdown mode, and very severe ones.
> 
Also I doesn’t understand why you post random years old and fixed CVEs. No software is perfect but you want enforce iMessage usage with Lockdown mode. So why not also for other/all software? Where’s the point?
Sounds only like an dislike against iMessage for non reason. 


> The security and privacy trade-offs with trusting Apple software ought to be better explained before the recommendation is made.
>
For me this sounds very Anti-Apple so what’s this guide then for?

**Comment by kimg45** [comment]
Apple has lots of [audits and certifications](https://support.apple.com/guide/certifications/intro-to-apple-security-assurance-apc3cea61877b) from third parties. In particular, iMessage is covered by [ISO/IEC 27001 and ISO/IEC 27018](https://www.bsigroup.com/en-IE/validate-bsi-issued-certificates/client-directory-profile/APPLE_-0047421507-000) according to Apple. macOS's cryptography certifications can be seen [here](https://support.apple.com/guide/certifications/macos-security-certifications-apc35eb3dc4fa/1/web/1.0). In their [blog post](https://security.apple.com/blog/imessage-pq3/) about the new encryption algorithm, they mention outside evaluations of the security of iMessage's encryption [here](https://security.apple.com/assets/files/Security_analysis_of_the_iMessage_PQ3_protocol_Stebila.pdf) and [here](https://security.apple.com/assets/files/A_Formal_Analysis_of_the_iMessage_PQ3_Messaging_Protocol_Basin_et_al.pdf). Just because it is closed source doesn't mean no one outside Apple ever sees the code, it's just not openly available to the public. Of course Apple also has its own internal team of security researchers that have access to the code. 

I can take it out, I just really think it's best to give instructions on how to secure iMessage the best way possible since a lot of people can only be reached on there. It's sort of a network effect problem. I know my whole family uses iMessage and that's the situation for a lot of people. It's also not immediately obvious that you need to turn on Advanced Data Protection and contact key verification and lockdown mode for the best security, so I think it's valuable to mention these things. With messengers you have to meet people where they're at and be realistic. Some people need to use WhatsApp, some need to use iMessage, etc.

**Comment by drduh** [comment]
> This isn’t a problem. Mostly „outside“ researchers are the ones who find CVEs in closed sources and sometimes even Reverse Engineering the Code so I can’t understand what you’re trying to argument here.

The argument is iMessage is closed source and proprietary, and Apple has been dragging their feet closing fixing which are found by external researchers. Look at some of the Project Zero bugs with 90 day disclosure deadlines to appreciate their attitude towards these findings. It really paints a very compelling picture of how vulnerabilities are treated and what incentives exist to fix them, or not. What is your personal first-hand experience with vendor risk management, and how do you think Apple's security program compares, respective to its size and budget?

> Also I doesn’t understand why you post random years old and fixed CVEs. No software is perfect but you want enforce iMessage usage with Lockdown mode. So why not also for other/all software? Where’s the point? Sounds only like an dislike against iMessage for non reason.

They're not random or years old. They are recent and highly relevant. They have been actively abused in the wild against journalists and political dissidents. The point of using Lockdown mode is a significant reduction in risk with using this application. Not all software needs such protection, because not all software is capable of receiving multiple prolifically and inherently dangerous media types from anyone on the Internet at any time without one's consent or even knowledge.

> For me this sounds very Anti-Apple so what’s this guide then for?

For individuals who critically analyze their choices to trust something or not, and do so piecemeal, rather than blindly and totally. This guide is not meant to be anti-Apple, but is it meant to be critical and perhaps at times even teetering on paranoid. That's the way I would like it to be, even at the expense of some mockery, or whatever.

Look, I understand iMessage is convenient and a rosy picture is presented about its security posture and assurances. Perhaps they are sufficient for most people doing most things. But to the wrong person a recommendation to use iMessage - without clearly explaining the certain risks of using it and what mitigations are available - will be irresponsible, as it can demonstrably increase attack surface and risk.

To make it more confusing, we're replacing a peer-reviewed and long-time trusted RTC recommendation without any apparent cause. Even an expert has qualified OTR as sufficient for most use. This leaves me at a loss as to why we're so vehemently trying to replace one for the other. Can we plainly state why iMessage is more secure, more private, or otherwise better than OTR, if we're going to justify this change? Or maybe the two can co-exist until we are all more informed on potential threats?

**Comment by drduh** [comment]
> Apple has lots of [certifications](https://support.apple.com/guide/certifications/intro-to-apple-security-assurance-apc3cea61877b) from third parties.

These are standard, almost boiler-plate compliance certifications which do not seriously attest to the actual security of a product, in my personal view. Anyone who has sat in a room with an auditor, and likely had to explain something as basic as public-key authentication to them, can attest to this fact. They are equivalent to saying something is secure because it has "encryption". Don't get me wrong, they are valuable, but only as business tools to make underwriters comfortable and sales moving.

The exception perhaps being FIPS 140-3 on the secure enclave, which is impressive, but not directly related to what we're discussing: software security. For a meaningful understanding of that, either direct access to source code, or a professional audit by a reputable firm is needed, or both. Apple will not even publish the iMessage protocol and by all accounts it is very difficult to reverse it.

> In particular, iMessage is covered by [ISO/IEC 27001 and ISO/IEC 27018](https://www.bsigroup.com/en-IE/validate-bsi-issued-certificates/client-directory-profile/APPLE_-0047421507-000).

Equifax also held ISO 27001 certification when it was breached. How do you think this qualification makes iMessage secure?

> macOS's cryptography certifications can be seen [here](https://support.apple.com/guide/certifications/macos-security-certifications-apc35eb3dc4fa/1/web/1.0). In their [blog post](https://security.apple.com/blog/imessage-pq3/) about the new encryption algorithm, they mention outside evaluations of the security of iMessage's encryption [here](https://security.apple.com/assets/files/Security_analysis_of_the_iMessage_PQ3_protocol_Stebila.pdf) and [here](https://security.apple.com/assets/files/A_Formal_Analysis_of_the_iMessage_PQ3_Messaging_Protocol_Basin_et_al.pdf).

The cryptography is not on trial here. It is rarely the problem because so many lower hanging fruit exist for adversaries, most do not even bother with learning it. I'll present the same challenge as @beerisgood here: why does quantum-resistance matter with iMessage but not every other encryption mentioned in the guide?

> Just because it is closed source doesn't mean no one outside Apple ever sees the code, it's just not openly available to the public. Of course Apple also has its own internal team of security researchers that have access to the code.

That Apple has a security team is not contested, whether they are capable and enabled to prioritize the interests of security and privacy over convenience and product development is. It seems we can only speculate about that for now.

> I can take it out, I just really think it's best to give instructions on how to secure iMessage the best way possible since a lot of people can only be reached on there. It's sort of a network effect problem. I know my whole family/all my friends use iMessage and that's the situation for a lot of people. It's also not immediately obvious that you need to turn on Advanced Data Protection and contact key verification and lockdown mode for the best security, so I think it's valuable to mention these things. With messengers you have to meet people where they're at and be realistic. Some people need to use WhatsApp, some need to use iMessage, etc.

Well, this is by design - https://www.zdnet.com/article/apple-confirms-imessage-locks-users-into-ios-and-putting-it-on-android-would-hurt-apple/: 

'Craig Federighi, Apple's Senior Vice President of Software Engineering and the executive in charge of iOS, went as far as to say that "iMessage on Android would simply serve to remove [an] obstacle to iPhone families giving their kids Android phones."'

So the network effect is further exacerbated by the recommendation. But we live in the real world and I sincerely agree with what you said, and find your suggestions helpful and practical. So iMessage is important: you are not wrong to bring it up and shouldn't remove your contributions. Let's simply present some evidence of whether it is any good by someone other than Apple.

**Comment by kimg45** [comment]
Well the expert recommended OMEMO over OTR, he only said OTR was acceptable if your threat model includes the administrator of your server and not a high resource organization like the NSA. I'll take out iMessage, I think we should listen to him and recommend OMEMO over OTR tho. There's no advantage to using OTR when OMEMO covers everything it does and more.

**Comment by drduh** [comment]
OMEMO can replace OTR.

Put the Signal recommendation back since it is much better than iMessage.

Remove the stuff about quantum-resistance (which is largely irrelevant) and E2EE: Apple can make those claims in their documentation but what cannot be indepdendently validated should not be in this guide.

Thank you again for taking the time to work on this and other changes.

**Comment by kimg45** [comment]
Done

**Pull request merged**
