### PR TITLE
Update preparing and installing macOS section

### PR DESCRIPTION
**Pull request by kimg45**
-Removed parts that are covered in Apple's documentation
-Removed outdated info
-Removed manually checking the certificate because Apple silicon Macs do so automatically without needing user input
-update first boot section
-remove rambly essay about how bad Apple is bc it doesn't really add any useful information

### CODE REVIEW

**Comment by drduh** [comment]
What is wrong with the alternative installation steps? It seems like a lot of potentially useful information to remove, judging from previous contributions to that section.

I know we discussed keeping the guide updated for the latest Apple releases, but I'm not sure everyone is off Intel Macs to warrant removing all relevant parts just yet. What do others think?

The rambly essay can be removed but reference it as an additional resource at least. There are significant privacy implications with using secure hardware, and those certain trade-offs ought to be better discussed and explained.

**Comment by kimg45** [comment]
Problems in order:
- recovery mode instructions don't work on Apple silicon. linked to the apple documentation so it stays updated and offers the best coverage for different Macs
- link to old version of macOS in the App Store. linked to the documentation instead of referencing specific versions so it doesn't go out of date
- [link](https://osxdaily.com/2020/04/13/how-download-full-macos-installer-terminal/) to third party and very outdated instructions on making a bootable USB, Apple provides instructions on making a bootable USB so I linked to that instead
- list of download links for older versions of macOS, this duplicates the official documentation needlessly so I deleted it
- no need to verify the signature with `codesign` since the secure enclave handles that for you
- instructions that duplicate [Apple's](https://support.apple.com/en-us/101578) documentation for making installation USB needlessly, linked to that instead
- instructions for creating an install image that the guide itself claims doesn't work so deleted it
- target disk mode replaced by revive/restore, could link to that but it's brought up later in the firmware part so I thought it was pointless to talk about it in two places
- recovery partition isn't needed + you need an internet connection now if you reinstall anyway, so might as well just use the network recovery
- macOS is most secure running on native Apple silicon, this extends to VMs as well so I replaced VMware Fusion with UTM which is free and doesn't require you to give them payment info, a guide about privacy should avoid software that requires personal info to use imo
- the guide itself says that disconnecting the network before install is pointless since the 2016 Touch Bar Macs started requiring online activation so removed that part
- intel nvram clearing irrelevant on Apple silicon
- replaced the XKCD comic with EFF link that is more detailed and we link to later in the guide

The essay is just highly overdramatic about a simple hardware identifier. You don't have to log in to your Apple ID, you don't have to give apple your payment info, you can just buy it in cash if you want. If it's a new Mac you don't even need to do the activation process anyway afaik it's only if you try to reinstall. I personally don't see any value in linking to it, it's mostly just trying to scare the reader into avoiding macOS which, why have that in a guide about macOS? It's really a lot of drama over nothing. I will add that this guide recommends like 10 different pieces of software that all 1. require payment information and 2. can see **all** of your network connections, so it seems strange to hyper fixate on this hardware identifier when those are much worse imo. Just my thoughts tho

**Review by beerisgood — COMMENTED** [review]
I would use the threat model version as most people doesn’t care if they’re need to connect their expensive device with their ID. 

So it’s an special threat model if this isn’t wanted.

**Comment by kimg45** [comment]
Added back the threat model mention.

**Comment by drduh** [comment]
Let's put VMware back. I understand some might not like it because it is for-profit software, which is a valid criticism, but it also has a proven track record of reliability. It at least deserves a mention after the UTM app is recommended, perhaps with even more alternative virtualization software listed. We can raise a separate issue to address non-free recommendations throughout the guide as well.

I insist on keeping at least a link to the "iOS, The Future Of macOS, Freedom, Security And Privacy In An Increasingly Hostile Global Environment" article. Yes, is it hyperbolic, but for obvious reasons. That other software requires payment or installs invasive components does not diminish its value. A single unique identifier in the hands of a very capable adversary can pose more risk than a dozen held by an incapable one. As you said, Apple silicon is the way forward for security, but it does require some privacy sacrifice.

The article's virtues and thesis should are best discussed in its respective comment section though. We should at least make it discoverable so readers can make up their own mind, and an opinionated take on this topic inspires critical thinking vs Apple's dry whitepaper. Threat modeling should be its own detailed section (or even guide) - feel free to open an issue to track this work. I would be glad to take the lead on it.

Thanks again for the lively discussion and all the modernization contributions you have been making. Keep the PRs coming!

**Comment by kimg45** [comment]
Alright I re added VMware with a link to their documentation on installing macOS and put the article in the additional resources section.

**Comment by beerisgood** [comment]
Yeah it’s nice to see updates here. Thanks also from my side @kimg45 

That's not supposed to sound negative, but are you planning to keep the guide up to date than it was before? After all, it seems to be the most well-known macOS guide  @drduh

**Comment by beerisgood** [comment]
It's already merged, but what's wrong with the tools from https://eclecticlight.co/virtualisation-on-apple-silicon/ and [Parallels](https://www.parallels.com/)?

**Comment by kimg45** [comment]
Eclectic light company on their downloads page list a lot of stuff that seems to be for very old versions of macOS? And a lot of their software seems to be like security snake oil kinda stuff. Idk can re add it I guess. Parallels is good, needs a subscription and stuff tho.

**Comment by beerisgood** [comment]
Fair enough 🍺

**Pull request merged**
