### PR TITLE
Remove defunct Little Flocker reference

### PR DESCRIPTION
**Pull request by ansell**
Little Flocker went away when its author joined Apple and sold Little Flocker off to F-Secure where it is undergoing redesign, but not useful for this guide at this point. 

https://www.imore.com/little-flocker-getting-dumbed-down-good-all-mac-users

### CODE REVIEW

**Comment by nadavP3** [comment]
The tool has been renamed by F-Secure from "Little Flocker" to "F-SECURE XFENCE"
and is available for free as beta here:
https://campaigns.f-secure.com/xfence/
It even still features the exact same user interface and functionality (just altered name and icon)
Still very useful, can help mitigate / prevent so many things since you need file access to encrypt files, add startup items, access sensitive data .. 

there are some "growing pains" (for a new user of this app) but once you setup all your usual softwares (can easily be done initially via enabling "learning mode" where it just auto accepts all access and later provides required rules for all of this to be accepted in the future) (+you can also set to allow software to keep its file access privilege /rules even if the binary is updated (via software update), which isn't AS secure but is very convenient.
so, once that all said and done, day to day you shouldn't expect any prompts from the app, but if a pdf file (or docx, or even that app you totally got not from an app store ...) tries to access your ~/pictures .. which it shouldn't ... you can just one click deny that .. 
I wouldn't pass up on this tool.

**Comment by ansell** [comment]
Sorry for any inference that the newly branded version was going to be lower quality (I still want to switch from my functioning Little Flocker to it in the future!).  I didn't have any teething issues with Little Flocker in Learning Mode so I am definitely not negative about it 👍 

Feel free to submit a separate PR with a reference to X-Fence Beta and I will close this one. 

Just wanted to remove the reference to Little Flocker given the status of it in that name.

**Comment by ansell** [comment]
The reference to "Not useful for this guide" was based on it being in a closed beta right now, not based on its usefulness in general if you did have access to the beta versions.

**Comment by nadavP3** [comment]
The one negative thing about the  X-Fence Beta beta is that to date, they haven't released any updates past the initial version.

Here is what they wrote in their download page:

> 
> **A notice to users of Little Flocker**
> 
> F-Secure XFENCE 1.6.6 is our initial beta version of XFENCE. Its current feature set is compatible with Little Flocker version 1.6.4. This first version of XFENCE will not be able to automatically migrate Little Flocker rules or preferences, nor will it be published as an automatic update to existing Little Flocker users.
> 
> Existing installations of Little Flocker will continue to function as before, **and once we have implemented migration of rules and preferences, they will be offered an automatic upgrade to F-Secure XFENCE beta.**

sounds great, however this was posted on April 17, 2017 (~4 months ago) and thats also the last post, 1.6.6 is still the version they offer to download.
Back when Mr. Zdziarski was running the show, he used to release an update practically every week if not faster than that.

I don't know what the future holds for LF/XF but the total lack of communication over past four months and zero signs of active development is not reassuring.

As for the guide, I'd just:
1. add this two links at the end of Little Flocker section:
https://techcrunch.com/2017/04/06/f-secure-buys-little-flocker-to-upgrade-its-mac-security-play/
https://campaigns.f-secure.com/xfence/
2. remove hyper link from dead links

can be something like this:
3. briefly state: "LF was sold to F-Secure, (see techcrunch for backstory), and is now available here (insert link).." and if the reader is up for it they can go and apply for the beta.. the whole "Firewall for your files" really sums it up.

**Comment by JayBrown** [comment]
There was a lot of activity, just not for the standalone security app. F-Secure has recently integrated XFENCE into their PSB Computer Protection for Mac, which is available only for business customers: https://help.f-secure.com/product.html#business/releasenotes-business/latest/en/fspsb_cp_mac-latest-en

Whether XFENCE will ever be integrated into one of their home security products, is unknown. Whether there will ever be updates and a regular release of the standalone XFENCE (f.k.a. "Little Flocker") isn't known either, but from my gut, I'd say it's highly unlikely. They bought it because they like the functionality.

So since Little Flocker is dead, and since—so we should assume—XFENCE SA is dead too, LF should be removed from guide, and not be replaced by a link to the XFENCE beta, until we know more (and something concrete) about the latter product's future.

**Comment by nadavP3** [comment]
@JayBrown Isn't there still some value in referencing the stand alone XFENCE software beta?
I am unaware of any other tool that can provide the same functionality, and despite the lack of updates it still functions on both Sierra and High Sierra (I am using it daily without any issues)

Naturally should an update to MacOS break it or if F-Secure chooses to stop providing this tool then there wouldn't be any reason to keep it

**Comment by JayBrown** [comment]
I'm using Little Flocker 1.6.4 on El Capitan, and it's running fine, so I assume the XFENCE beta is too, because it's the same product, just with different graphics. ;) But to be honest, the software is still quite raw and needs a *lot* of work & finetuning. F-Secure were wise of adding the beta status again. So I guess you could reference XFENCE in the guide, but maybe note that it's beta and might not be developed further. At any rate Little Flocker and littleflocker.com need to be replaced. (It's still mentioned under "Related software".)

**Comment by nadavP3** [comment]
F-Secure just lunched an update for Little Flocker (v1.6.2/latest) that migrate it to XFENCE (beta v1.8.88/latest) 

I am happy to see signs of life for this product, hopefully it will remain available as a standalone solution. 

lfv162updatemsg

**Pull request merged**
