### PR TITLE
Remove OpenBSM audit

### PR DESCRIPTION
**Pull request by kimg45**
The man pages say all of these commands are deprecated and scheduled for removal.

### CODE REVIEW

**Comment by drduh** [comment]
The commands haven't yet been removed though, right? Is there a replacement endpoint security mechanism which can be referenced? This is valuable functionality that's been around since the PowerPC days and it would be a shame to lose it.

**Comment by kimg45** [comment]
> The commands haven't yet been removed though, right? Is there a replacement endpoint security mechanism which can be referenced? This is valuable functionality that's been around since the PowerPC days and it would be a shame to lose it.

Well it says it's already been disabled in 14. It says to use the EndPoint Security API but that's an API not commands.

**Comment by drduh** [comment]
I saw that, but there are [recent instructions](https://derflounder.wordpress.com/2023/10/18/re-enabling-openbsm-auditing-on-macos-sonoma/) available to re-enable functionality, which may indicate people still use it.

Although I don't think DTrace works under SIP anymore, either. IMO the System monitoring section should be re-written as Endpoint security, with modern solutions offered, and the Antivirus section rolled in to it.

**Comment by kimg45** [comment]
Good idea

**Comment by drduh** [comment]
> Good idea. Think OpenBSM should be kept tho? Seems like a bad idea to recommend deprecated features.

I think only if they pose a risk. In this case, it's first party software which appears to be in the process of being replaced with new functionality. We should document both during the transition, and remove it once auditd is officially no longer available. Does that make sense?

**Pull request closed without merging**
