### PR TITLE
Miscellaneous update

### PR DESCRIPTION
**Pull request by kimg45**
- change disable diagnostics link to official documentation
- remove duti which hasn't been updated in a decade
- remove deleted article about bonjour
- change handoff/bluetooth links to official documentation
- replace outdated sandbox links with instructions to check if apps are using App Sandbox
- remove mention of TPM since Macs use the Secure Enclave which is much better than a TPM anyway
- update umask link
- change references to bash to zsh

### CODE REVIEW

**Comment by drduh** [comment]
I would keep disabling bonjour as it reduces the network profile. It's also a part of the NIST guidelines https://github.com/usnistgov/macos_security/blob/main/rules/os/os_bonjour_disable.yaml

Is there an alternative to duti we can recommend? The samba stuff is probably less relevant, but changing the default handler for executables to TextEdit still seems valuable.

Why remove the umask recommended setting of 077? The Apple docs are appreciated, but stop short of making the suggestion.

**Comment by beerisgood** [comment]
Without Bonjour you can’t use AirPlay and AirPrint: https://support.apple.com/guide/deployment/dep9151c4ace/web

What’s the matter for modify (executive) handler? It’s not Windows where you can start an .exe with double click. 

Did anyone really use umask? Even Apple warns against it:
> Be careful when you change file permissions and umasks. If you make a mistake, you can lower the security of files, folders, or apps on your Mac, or prevent apps from working.

**Comment by kimg45** [comment]
Re added the custom umask instructions and disabling bonjour. You can literally just set any type of file to open with any program natively in macOS so there's no need for a third party program like duti.

**Comment by drduh** [comment]
> What’s the matter for modify (executive) handler? It’s not Windows where you can start an .exe with double click.

Pretty sure it's exactly so. Try creating a bash script and saving the file without an extension, then double-click on it to see what happens. If it runs in terminal, we should make explicit instructions for changing the handler, as some readers may not know what qualifies as an "executable file".

We should add a warning for the bonjour features.

**Comment by kimg45** [comment]
Yeah executable could be a lot of things. Are you thinking like terminal scripts only?

**Pull request merged**
