### PR TITLE
outdated "DNS - hosts file" part replaced with DNS profiles

### PR DESCRIPTION
**Pull request by beerisgood**
using the hosts file for filtering etc. is not a sensible or safe way and causes more problems than it solves.
also a long list reduces performance and "thanks" to IPv6 the whole management is too cumbersome and not recommended for normal users

### CODE REVIEW

**Comment by drduh** [comment]
Can you cite some information about DNS profiles, perhaps a little about how it works?

**Comment by beerisgood** [comment]
> Can you cite some information about DNS profiles, perhaps a little about how it works?

Here or as PR in your guide ?

**Comment by drduh** [comment]
PR would be best, but if you add it here I can work on it also.

**Comment by beerisgood** [comment]
Alright. Some links:

https://support.apple.com/en-us/HT209435

https://support.quad9.net/hc/en-us/articles/360057889591-Setup-iOS-DNS-over-HTTPS-or-DNS-over-TLS

https://dns.notjakob.com/

https://github.com/paulmillr/encrypted-dns

**Comment by troian** [comment]
those are DNS servers with some benefits.
also list is missing Pi-Hole

tho I agree editing `/etc/hosts` is a bad idea - there is still some use for it.

**Comment by beerisgood** [comment]
> those are DNS servers with some benefits. also list is missing Pi-Hole
> 

PiHole isn’t recommend for many reasons and doesn’t work by default with devices outside your home. 

> tho I agree editing `/etc/hosts` is a bad idea - there is still some use for it.
>

I can’t even see one useful thing for normal user.

**Comment by troian** [comment]
> PiHole isn’t recommend for many reasons and doesn’t work by default with devices outside your home.
I'm not sure what is meant to be said in this. A phone that is not in the home Wifi network when you are away?
I don't think Pi-Hole has been designed to deal with it.

> I can’t even see one useful thing for normal user.
This guide is not for a normal user, for sure 😉

**Comment by drduh** [comment]
I would recommend keeping the hosts method unless that stops working or causes a demonstrable issue.

**Comment by beerisgood** [comment]
Should I rebuild the PR than so both profiles and hosts file is included?

**Comment by drduh** [comment]
> Should I rebuild the PR than so both profiles and hosts file is included?

Yes, keep the original hosts stuff for now.

**Comment by beerisgood** [comment]
> > Should I rebuild the PR than so both profiles and hosts file is included?
> 
> Yes, keep the original hosts stuff for now.

Done.

**Pull request merged**
